/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilitiesDotmdRouteImport } from './routes/utilities[.]md'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RegistryDotjsonRouteImport } from './routes/registry[.]json'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as DocsDotmdRouteImport } from './routes/docs[.]md'
import { Route as ComponentsDotmdRouteImport } from './routes/components[.]md'
import { Route as BlocksDotmdRouteImport } from './routes/blocks[.]md'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtilitiesIndexRouteImport } from './routes/utilities.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as BlocksIndexRouteImport } from './routes/blocks.index'
import { Route as UtilitiesChar123nameChar125DotmdRouteImport } from './routes/utilities.{$name}[.]md'
import { Route as UtilitiesNameRouteImport } from './routes/utilities.$name'
import { Route as RChar123nameChar125DotjsonRouteImport } from './routes/r/{$name}[.]json'
import { Route as RRegistryDotjsonRouteImport } from './routes/r/registry[.]json'
import { Route as DocsChar123slugChar125DotmdRouteImport } from './routes/docs.{$slug}[.]md'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as ComponentsChar123nameChar125DotmdRouteImport } from './routes/components.{$name}[.]md'
import { Route as ComponentsNameRouteImport } from './routes/components.$name'
import { Route as BlocksChar123nameChar125DotmdRouteImport } from './routes/blocks.{$name}[.]md'
import { Route as BlocksNameRouteImport } from './routes/blocks.$name'

const UtilitiesDotmdRoute = UtilitiesDotmdRouteImport.update({
  id: '/utilities.md',
  path: '/utilities.md',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryDotjsonRoute = RegistryDotjsonRouteImport.update({
  id: '/registry.json',
  path: '/registry.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDotmdRoute = DocsDotmdRouteImport.update({
  id: '/docs.md',
  path: '/docs.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDotmdRoute = ComponentsDotmdRouteImport.update({
  id: '/components.md',
  path: '/components.md',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksDotmdRoute = BlocksDotmdRouteImport.update({
  id: '/blocks.md',
  path: '/blocks.md',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesIndexRoute = UtilitiesIndexRouteImport.update({
  id: '/utilities/',
  path: '/utilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesChar123nameChar125DotmdRoute =
  UtilitiesChar123nameChar125DotmdRouteImport.update({
    id: '/utilities/{$name}.md',
    path: '/utilities/{$name}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const UtilitiesNameRoute = UtilitiesNameRouteImport.update({
  id: '/utilities/$name',
  path: '/utilities/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RChar123nameChar125DotjsonRoute =
  RChar123nameChar125DotjsonRouteImport.update({
    id: '/r/{$name}.json',
    path: '/r/{$name}.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const RRegistryDotjsonRoute = RRegistryDotjsonRouteImport.update({
  id: '/r/registry.json',
  path: '/r/registry.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123slugChar125DotmdRoute =
  DocsChar123slugChar125DotmdRouteImport.update({
    id: '/docs/{$slug}.md',
    path: '/docs/{$slug}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsChar123nameChar125DotmdRoute =
  ComponentsChar123nameChar125DotmdRouteImport.update({
    id: '/components/{$name}.md',
    path: '/components/{$name}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsNameRoute = ComponentsNameRouteImport.update({
  id: '/components/$name',
  path: '/components/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksChar123nameChar125DotmdRoute =
  BlocksChar123nameChar125DotmdRouteImport.update({
    id: '/blocks/{$name}.md',
    path: '/blocks/{$name}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlocksNameRoute = BlocksNameRouteImport.update({
  id: '/blocks/$name',
  path: '/blocks/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks.md': typeof BlocksDotmdRoute
  '/components.md': typeof ComponentsDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/utilities.md': typeof UtilitiesDotmdRoute
  '/blocks/$name': typeof BlocksNameRoute
  '/blocks/{$name}.md': typeof BlocksChar123nameChar125DotmdRoute
  '/components/$name': typeof ComponentsNameRoute
  '/components/{$name}.md': typeof ComponentsChar123nameChar125DotmdRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/{$slug}.md': typeof DocsChar123slugChar125DotmdRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/utilities/$name': typeof UtilitiesNameRoute
  '/utilities/{$name}.md': typeof UtilitiesChar123nameChar125DotmdRoute
  '/blocks/': typeof BlocksIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/utilities/': typeof UtilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks.md': typeof BlocksDotmdRoute
  '/components.md': typeof ComponentsDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/utilities.md': typeof UtilitiesDotmdRoute
  '/blocks/$name': typeof BlocksNameRoute
  '/blocks/{$name}.md': typeof BlocksChar123nameChar125DotmdRoute
  '/components/$name': typeof ComponentsNameRoute
  '/components/{$name}.md': typeof ComponentsChar123nameChar125DotmdRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/{$slug}.md': typeof DocsChar123slugChar125DotmdRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/utilities/$name': typeof UtilitiesNameRoute
  '/utilities/{$name}.md': typeof UtilitiesChar123nameChar125DotmdRoute
  '/blocks': typeof BlocksIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/utilities': typeof UtilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks.md': typeof BlocksDotmdRoute
  '/components.md': typeof ComponentsDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/utilities.md': typeof UtilitiesDotmdRoute
  '/blocks/$name': typeof BlocksNameRoute
  '/blocks/{$name}.md': typeof BlocksChar123nameChar125DotmdRoute
  '/components/$name': typeof ComponentsNameRoute
  '/components/{$name}.md': typeof ComponentsChar123nameChar125DotmdRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/{$slug}.md': typeof DocsChar123slugChar125DotmdRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/utilities/$name': typeof UtilitiesNameRoute
  '/utilities/{$name}.md': typeof UtilitiesChar123nameChar125DotmdRoute
  '/blocks/': typeof BlocksIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/utilities/': typeof UtilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks.md'
    | '/components.md'
    | '/docs.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/registry.json'
    | '/robots.txt'
    | '/utilities.md'
    | '/blocks/$name'
    | '/blocks/{$name}.md'
    | '/components/$name'
    | '/components/{$name}.md'
    | '/docs/$slug'
    | '/docs/{$slug}.md'
    | '/r/registry.json'
    | '/r/{$name}.json'
    | '/utilities/$name'
    | '/utilities/{$name}.md'
    | '/blocks/'
    | '/components/'
    | '/docs/'
    | '/utilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks.md'
    | '/components.md'
    | '/docs.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/registry.json'
    | '/robots.txt'
    | '/utilities.md'
    | '/blocks/$name'
    | '/blocks/{$name}.md'
    | '/components/$name'
    | '/components/{$name}.md'
    | '/docs/$slug'
    | '/docs/{$slug}.md'
    | '/r/registry.json'
    | '/r/{$name}.json'
    | '/utilities/$name'
    | '/utilities/{$name}.md'
    | '/blocks'
    | '/components'
    | '/docs'
    | '/utilities'
  id:
    | '__root__'
    | '/'
    | '/blocks.md'
    | '/components.md'
    | '/docs.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/registry.json'
    | '/robots.txt'
    | '/utilities.md'
    | '/blocks/$name'
    | '/blocks/{$name}.md'
    | '/components/$name'
    | '/components/{$name}.md'
    | '/docs/$slug'
    | '/docs/{$slug}.md'
    | '/r/registry.json'
    | '/r/{$name}.json'
    | '/utilities/$name'
    | '/utilities/{$name}.md'
    | '/blocks/'
    | '/components/'
    | '/docs/'
    | '/utilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksDotmdRoute: typeof BlocksDotmdRoute
  ComponentsDotmdRoute: typeof ComponentsDotmdRoute
  DocsDotmdRoute: typeof DocsDotmdRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RegistryDotjsonRoute: typeof RegistryDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  UtilitiesDotmdRoute: typeof UtilitiesDotmdRoute
  BlocksNameRoute: typeof BlocksNameRoute
  BlocksChar123nameChar125DotmdRoute: typeof BlocksChar123nameChar125DotmdRoute
  ComponentsNameRoute: typeof ComponentsNameRoute
  ComponentsChar123nameChar125DotmdRoute: typeof ComponentsChar123nameChar125DotmdRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DocsChar123slugChar125DotmdRoute: typeof DocsChar123slugChar125DotmdRoute
  RRegistryDotjsonRoute: typeof RRegistryDotjsonRoute
  RChar123nameChar125DotjsonRoute: typeof RChar123nameChar125DotjsonRoute
  UtilitiesNameRoute: typeof UtilitiesNameRoute
  UtilitiesChar123nameChar125DotmdRoute: typeof UtilitiesChar123nameChar125DotmdRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  UtilitiesIndexRoute: typeof UtilitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilities.md': {
      id: '/utilities.md'
      path: '/utilities.md'
      fullPath: '/utilities.md'
      preLoaderRoute: typeof UtilitiesDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry.json': {
      id: '/registry.json'
      path: '/registry.json'
      fullPath: '/registry.json'
      preLoaderRoute: typeof RegistryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs.md': {
      id: '/docs.md'
      path: '/docs.md'
      fullPath: '/docs.md'
      preLoaderRoute: typeof DocsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components.md': {
      id: '/components.md'
      path: '/components.md'
      fullPath: '/components.md'
      preLoaderRoute: typeof ComponentsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks.md': {
      id: '/blocks.md'
      path: '/blocks.md'
      fullPath: '/blocks.md'
      preLoaderRoute: typeof BlocksDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/': {
      id: '/utilities/'
      path: '/utilities'
      fullPath: '/utilities/'
      preLoaderRoute: typeof UtilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/{$name}.md': {
      id: '/utilities/{$name}.md'
      path: '/utilities/{$name}.md'
      fullPath: '/utilities/{$name}.md'
      preLoaderRoute: typeof UtilitiesChar123nameChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/$name': {
      id: '/utilities/$name'
      path: '/utilities/$name'
      fullPath: '/utilities/$name'
      preLoaderRoute: typeof UtilitiesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/{$name}.json': {
      id: '/r/{$name}.json'
      path: '/r/{$name}.json'
      fullPath: '/r/{$name}.json'
      preLoaderRoute: typeof RChar123nameChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/registry.json': {
      id: '/r/registry.json'
      path: '/r/registry.json'
      fullPath: '/r/registry.json'
      preLoaderRoute: typeof RRegistryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$slug}.md': {
      id: '/docs/{$slug}.md'
      path: '/docs/{$slug}.md'
      fullPath: '/docs/{$slug}.md'
      preLoaderRoute: typeof DocsChar123slugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/{$name}.md': {
      id: '/components/{$name}.md'
      path: '/components/{$name}.md'
      fullPath: '/components/{$name}.md'
      preLoaderRoute: typeof ComponentsChar123nameChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$name': {
      id: '/components/$name'
      path: '/components/$name'
      fullPath: '/components/$name'
      preLoaderRoute: typeof ComponentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/{$name}.md': {
      id: '/blocks/{$name}.md'
      path: '/blocks/{$name}.md'
      fullPath: '/blocks/{$name}.md'
      preLoaderRoute: typeof BlocksChar123nameChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$name': {
      id: '/blocks/$name'
      path: '/blocks/$name'
      fullPath: '/blocks/$name'
      preLoaderRoute: typeof BlocksNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksDotmdRoute: BlocksDotmdRoute,
  ComponentsDotmdRoute: ComponentsDotmdRoute,
  DocsDotmdRoute: DocsDotmdRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RegistryDotjsonRoute: RegistryDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  UtilitiesDotmdRoute: UtilitiesDotmdRoute,
  BlocksNameRoute: BlocksNameRoute,
  BlocksChar123nameChar125DotmdRoute: BlocksChar123nameChar125DotmdRoute,
  ComponentsNameRoute: ComponentsNameRoute,
  ComponentsChar123nameChar125DotmdRoute:
    ComponentsChar123nameChar125DotmdRoute,
  DocsSlugRoute: DocsSlugRoute,
  DocsChar123slugChar125DotmdRoute: DocsChar123slugChar125DotmdRoute,
  RRegistryDotjsonRoute: RRegistryDotjsonRoute,
  RChar123nameChar125DotjsonRoute: RChar123nameChar125DotjsonRoute,
  UtilitiesNameRoute: UtilitiesNameRoute,
  UtilitiesChar123nameChar125DotmdRoute: UtilitiesChar123nameChar125DotmdRoute,
  BlocksIndexRoute: BlocksIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  UtilitiesIndexRoute: UtilitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
